export const NOTIFICAR = 'NOTIFICAR';

export const DEFINE_USUARIO_LOGADO = 'DEFINE_USUARIO_LOGADO';
export const DESLOGAR_USUARIO = 'DESLOGAR_USUARIO';

export const OBTER_ANOTACOES = 'OBTER_ANOTACOES';
export const ADICIONA_ANOTACAO = 'ADICIONA_ANOTACAO';
export const ALTERA_ANOTACAO = "ALTERA_ANOTACAO";
export const DELETA_ANOTACAO = "DELETA_ANOTACAO";