export const EFETUAR_LOGIN = "EFETUAR_LOGIN";

export const CARREGAR_ANOTACOES = "CARREGAR_ANOTACOES";
export const CADASTRAR_ANOTACAO = "CADASTRAR_ANOTACAO";
export const ATUALIZAR_ANOTACAO = "ATUALIZAR_ANOTACAO";
export const DELETAR_ANOTACAO = "DELETAR_ANOTACAO";